name: "Terraform"

on:
  push:
    branches:
      - main
    paths:
      - 'base_infra/**'

  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      # - name: Set AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ZTNA }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ZTNA }}
      #     aws-region: us-west-2

      - name: deploy to cluster
        uses: wahyd4/kubectl-helm-action@master

      - name: environement-setup
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
#git remote add origin https://github.com/Zeeshan50522/terraform-eks-gitop.git
